### ISSUE TITLE
Does this still work for Safari (Yosemite)? 

### ISSUE THREAD

**Issue by tconroy** [kunklejr/ssl-everywhere.safariextension#5]
Want to know before attempting to install it. Looking for an HTTPS Everywhere equivalent for Safari but it seems Safari doesn't allow safe rewriting of HTTP to HTTPS in address bar links. This is the closest project I could find which claims to do so.

**Comment by heubergen** [comment]
Yes it works, I tested it under 10.11.1 with Safari 9.

May I add some rolls in the future.
